compile:
  libraries:
    - s-t-a-n--Structures
    - Spine--Filters
    - Spine--Timers
    - Spine--ROS-Generated
    - TinyGPS
    - LSM303
    - OneWire
    - DallasTemperature
  platforms:
    - mega2560

unittest:
  libraries:
    - s-t-a-n--Structures
    - Spine--Filters
    - Spine--Timers
    - Spine--ROS-Generated
    - TinyGPS
    - LSM303
  platforms:
    - mega2560

platforms:
  mega2560:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR__
        - __AVR_ATmega2560__
        - ARDUINO_ARCH_AVR
        - ARDUINO_AVR_MEGA2560
        - ARDUINO_CI
        - ROS # for testing with ROS subcomponents
      warnings:
      flags:
